### ISSUE TITLE
Question mark on each feature

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#112]
On the original wireframe there is a question mark on each idem of the table, when you hover on the question mark a small tooltips elaborates more on that feature.

That content of the tooltip needs to be sourced from YML, here is the content:
https://docs.google.com/document/d/1exKtSmI8InZA8JKt4W3zZi1AajlxxziBOUVsjkF2n7E/edit#heading=h.yyoiuvcdxmfx

![Gatsby Storybook Starter · 4Geeks Academy](https://user-images.githubusercontent.com/426452/78667104-5f7aa980-78a6-11ea-8cb0-1dfddb50bd4f.png)

**Comment by plucodev** [comment]
This issue is fixed!
