### ISSUE TITLE
Center the "view all projects"

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#117]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3073-12546-e744b614b95300643eb668bb466497fe) 
 %!s(<nil>) 

---
**Source URL**:
[http://localhost:8000/](http://localhost:8000/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 80.0.3987.163</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x729</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by plucodev** [comment]
Issue Fixed
