### ISSUE TITLE
Company logos padding

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#123]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3073-12556-a6f5369aabad759a4a0c4709b0c306b2) 
 %!s(<nil>) 

---
**Source URL**:
[http://localhost:8000/us/partners/](http://localhost:8000/us/partners/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 80.0.3987.163</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920x729</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by plucodev** [comment]
fixed
