### ISSUE TITLE
Add students links and project links

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#228]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3073-16635-db351bcc61aecdef518e4671afa3aafc) 

 If the LinkedIn and/or Github is available add the links on the student information.

If the project live link exists adde it to the project infor.

If the video exists, add a button on the project an also a "play" button on the project picture.

---
**Source URL**:
[http://localhost:8000/](http://localhost:8000/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.116</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1910x685</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by plucodev** [comment]
Fixed the github and Linkedin buttons.
The PLAY button conditional already exists but need to be fixed because he doesn't accept all the video formats.

**Comment by alesanchezr** [comment]
What about live link?
