### ISSUE TITLE
Linkedin profile on testimonials

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#247]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3073-16884-b7db51df6bce69a9132ac003b1cd3e3e) 

---
**Source URL**:
[https://dev.4geeksacademy.co/](https://dev.4geeksacademy.co/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.116</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1711x746</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
So I already added to some of the textimonials in the YML the `linkedin` field, its just a matter of showing it on the website.

**Comment by plucodev** [comment]
@alesanchezr I am leaving it open so we can review tomorrow together
