### ISSUE TITLE
New version of the program details (syllabus)

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#250]
![Y4eo4Jw3d3 (1)](https://user-images.githubusercontent.com/426452/87709890-f6db7c80-c772-11ea-99ea-d3202955b390.gif)

**Comment by plucodev** [comment]
<img width="1379" alt="Screen Shot 2020-07-21 at 12 00 52 PM" src="https://user-images.githubusercontent.com/44124290/88077990-e7c94580-cb49-11ea-8327-f5dffd35fbbf.png">
