### ISSUE TITLE
[1pt] Bottom bar on the blog

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#348]
People reading the blog have no idea about 4geeks (some times), the bottom bar call to cation should be a banner that invites you to learn to code, not about the upcoming cohorts.

**Comment by alesanchezr** [comment]
@plucodev Basically you have to create a new LayoutBlog component, similar to the LayoutLanding that we already have.

**Comment by plucodev** [comment]
The top bar text should be something like this:
Become a web developer in 16 weeks
Covertiate en desarollador in 16 semanas

**Comment by plucodev** [comment]
we need to Break the title line with \n in the yml

**Comment by plucodev** [comment]
Need to add the same bar when the user is reading  a post.
