### ISSUE TITLE
Section program 9 weeks (in spanish)

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#358]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20256-4e54d4cb3fcb13a79d10dcd5d030bd68) 

 Our students said that we should indicate (maybe with a hover) that these are buttons, I mean i never thought that i had to clic in each hour to see more information. Hours are incorrect, in Spain we start at 9 and finish at 6.

---
**Source URL**:
[https://4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time](https://4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x529</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>80%</td></tr></table>

**Comment by alesanchezr** [comment]
duplicated #373
