### ISSUE TITLE
Está en inglés y se supone que es la web en español

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#361]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20391-97561cc02813caa0bd17daa419b17fce) 

 https://4geeksacademy.co/es/la-academia

---
**Source URL**:
[https://4geeksacademy.co/es/la-academia](https://4geeksacademy.co/es/la-academia)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x578</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>80%</td></tr></table>

**Comment by alesanchezr** [comment]
Eso lo cambias en los yml!
