### ISSUE TITLE
En versión móvil se salen las letras de los cuadros

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#367]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20395-a842637e4adc1e787cee2ff03a1b89e7) 

 Y además tenemos cosas solo en mayúsculas

---
**Source URL**:
[https://4geeksacademy.co/es/inicio](https://4geeksacademy.co/es/inicio)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x578</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>80%</td></tr></table>

**Comment by alesanchezr** [comment]
@plucodev lets decrease front size a little but, try testing this on the same browser and viewport size as reported.
