### ISSUE TITLE
Se ve muy mal

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#371]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20401-0a918301ad83c4633eb422ea92bfbbaf) 

---
**Source URL**:
[https://dev.4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time](https://dev.4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x578</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
Tienes q ser mas especifico, esto no me dice nada...

**Comment by victormgomezp** [comment]
Pues uno está abajo el otro super más arriba y el siguiente está también a otro nivel, no sé si hablamos de que el diseño es así pero da la sensación de que está mal
