### ISSUE TITLE
La gente no entiende que hay que cliquear y los iconos no tienen nada que ver

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#373]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20403-a4eab348a2c1d96ae28a4341e54a9693) 

 Urge mejorar los íconos (muchos no tienen nada que ver con lo que se explica). Poner o un hover o tiempo, la gente no entiende que hay que darle clic. He ajustado los horarios a España en la PR.

---
**Source URL**:
[https://dev.4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time](https://dev.4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x578</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
@plucodev lets do the same we did on the syllabus, lets automatically rotate this icons.
