### ISSUE TITLE
[1pt] Esta imagen debe estar en español

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#374]
Hrs <hrs>1</hrs>

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20404-7917a9ac4c0afaf69eb9751a7db1cf87) 

---
**Source URL**:
[https://dev.4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time](https://dev.4geeksacademy.co/es/course/desarrollo-web-full-stack-bootcamp-full-time)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x578</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
@plucodev since this is an SVG we are able to translate the text, we can render it dynamically like a react component and use YML for translations.

**Comment by plucodev** [comment]
@Omonroy36 the SVG texts are not like "text". Can you give me an SVG that contains the text like text, instead of a bunch of numbers like this one in the screenshot
<img width="1481" alt="Screen Shot 2020-11-06 at 10 29 41 AM" src="https://user-images.githubusercontent.com/44124290/98383875-0b41ce80-201b-11eb-9293-1666492b4d60.png">
?

**Comment by Omonroy36** [comment]
@plucodev this is the new svg with text paths as requested, tell if this works for you [https://drive.google.com/file/d/1qyLoMPYisYrqXk5RGBr5iyiOPE-pFU3W/view?usp=sharing](url)

**Comment by Jtoledo88** [comment]
@alesanchezr este issue fue hecho por @Omonroy36 esta terminado? cuantas horas son?

**Comment by alesanchezr** [comment]
un hora y ya se termino.

**Comment by Jtoledo88** [comment]
Aprobado y pagado!

**Comment by plucodev** [comment]
@tommygonzaleza Please add the spanish translation to programSvg.es.yaml

**Comment by Omonroy36** [comment]
@victormgomezp  you should close this issue since is already resolved
