### ISSUE TITLE
Este texto debe ir en comillas 

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#377]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20406-addd20b6d6d750cf51635be03a0dfb01) 

 Sección: Sobre la Academia · 4Geeks Academy

---
**Source URL**:
[https://dev.4geeksacademy.co/es/aliados](https://dev.4geeksacademy.co/es/aliados)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x578</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
@victormgomezp parece que esto lo puedes corregir tu no? Ponle las comillas en la traduccion!
