### ISSUE TITLE
Feísima la diagramación del blog

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#384]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-5094-20412-14fc581ca77562f8b27e6b36aff0ae8d) 

 La experiencia con el diseño es terrible, debería organizarse por fecha de las más recientes a las más antiguas, da sensación de abandono. 

---
**Source URL**:
[https://4geeksacademy.co/es/blog-en-espanol](https://4geeksacademy.co/es/blog-en-espanol)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.121</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1280x720</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280x578</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1.5x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by alesanchezr** [comment]
Esto todavia lo ves mal? Yo lo veo bien... @victormgomezp

**Comment by victormgomezp** [comment]
> Esto todavia lo ves mal? Yo lo veo bien... @victormgomezp

lo he visto desde la mía, como incógnito, borrando caché y desde la de gonzalo, y se ve mal.
