### ISSUE TITLE
Legal is not in the spanish version

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/website-v2#433]
This is the English version
![image](https://user-images.githubusercontent.com/48845580/97083423-50f7a380-15e6-11eb-853c-16fc01298b43.png)

This is the Spanish version
![image](https://user-images.githubusercontent.com/48845580/97083443-74bae980-15e6-11eb-9c28-c49de5ca2a3a.png)

Is important that the privacy policy is available for all the campus

**Comment by plucodev** [comment]
@victormgomezp you need to add the spanish privacy-policy

**Comment by plucodev** [comment]
@victormgomezp did you create the spanish content?

**Comment by victormgomezp** [comment]
Legal Advice is here:

https://drive.google.com/file/d/1PRDPlBgEfN4JVJRRcUtL1lPCLZNxJ_vH/view?usp=sharing
