### ISSUE TITLE
How can we allow more characters on the website team bio?

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#449]
Right now its just to little characters, here is an example of what we should allow:

![Screen Shot 2020-11-03 at 3 12 49 PM](https://user-images.githubusercontent.com/426452/98035829-18767780-1de7-11eb-829b-fe418fa5f1c9.png)

**Comment by plucodev** [comment]
Need to add the validation to test the maximum amount of characters in the staff.yml
