### ISSUE TITLE
Social Media tasks on thank-you page

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#452]
After the students applies to the academy, on the thank-you page, we should add a better thank you message and a list of places to follow us on social media.

After the person "checks" on the checkbox a button shows up that says E.g: "Take me to instagram"

<img width="548" alt="Screenshot 2020-11-03 at 23 17 21" src="https://user-images.githubusercontent.com/426452/98837866-7cb1c080-2411-11eb-86c8-5e107daae05d.png">

@victormgomezp can you confirm this is what you guys suggested?

**Comment by victormgomezp** [comment]
@alesanchezr yes, is something like that but remember that we have to bring them to local social media.

And try to use corporative colors.

**Comment by plucodev** [comment]
- Need to move the Read our blog button inside the social list

- decrease Follow up size

- put follow us title closer to the paragraph on the top
