### ISSUE TITLE
Spanglish in the table

### ISSUE THREAD

**Issue by jatv93** [4GeeksAcademy/website-v2#457]
![image](https://user-images.githubusercontent.com/48845580/99438463-990e9b00-28f2-11eb-8be8-d06698449944.png)

Strong local and remote, shouldn't be there as it is the Spanish version

**Comment by alesanchezr** [comment]
Esto viene de un YML, creo que tu misma puedes arreglarlo.

**Comment by jatv93** [comment]
Listo
