### ISSUE TITLE
There is no padding here

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#477]
We need padding here

![image](https://user-images.githubusercontent.com/62053368/102391358-e35c6800-3fd5-11eb-829d-54078b7def80.png)

**Comment by plucodev** [comment]
Hrs: <hrs>.1</hrs>

**Comment by tommygonzaleza** [comment]
This issue is already fixed, you can check at the [website](https://4geeksacademy.co/es/inicio)

**Comment by victormgomezp** [comment]
there is no chance, i have oppened in a incognito mode and deleting cache

url that you have to check is: https://4geeksacademy.co/es/inicio

![image](https://user-images.githubusercontent.com/62053368/103641012-57dd5380-4f51-11eb-9a7c-00035c804492.png)

**Comment by alesanchezr** [comment]
aprobado

**Comment by victormgomezp** [comment]
@plucodev is nos solved my friend 
![image](https://user-images.githubusercontent.com/62053368/112002818-9631ea00-8b20-11eb-8861-66f91f181819.png) this is how i see in incognit mode
