### ISSUE TITLE
GDPR & EU Cookies Directive ... MANDATORY AND URGENT: pop up to people from Europe that enter in the website explaining cookies

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#485]
Hrs: <hrs>8</hrs>

This is mandatory for everybody that visit the website and comes from Europe, we need a similar pop up

4Geeks Academy utiliza cookies propias y de terceros para fines analíticos, de personalización y para mostrarte publicidad personalizada en base a un perfil elaborado a partir de tus hábitos de navegación (por ejemplo, páginas visitadas) Puedes aceptar todas las cookies pulsando el botón “Aceptar todas y continuar” o configurarlas o rechazar su uso clicando en el botón “Configurar Cookies”. Si deseas obtener información más detallada, consulta nuestraPolítica de Cookies

![image](https://user-images.githubusercontent.com/62053368/103677934-372df180-4f83-11eb-954f-20f3043122b4.png)
![image](https://user-images.githubusercontent.com/62053368/103678206-8b38d600-4f83-11eb-99a6-e16446ee8cfc.png)

If we clic on "Configurar cookies" we should be capable to decide what kind of cookies we want to active, see the pictures and explanation of each type:

![image](https://user-images.githubusercontent.com/62053368/103678361-b91e1a80-4f83-11eb-9880-d857e6229a5d.png)

Here we have some examples of cookies that we could have in our site, we just have to explain what we have. 

Cookies técnicas:

Estas cookies permiten al usuario la navegación a través de nuestra web y la utilización de las diferentes opciones o servicios que existen en ella, incluyendo aquellas que Telefónica utiliza para permitir la gestión y operativa de la página web y habilitar sus funciones y servicios, como por ejemplo identificar la sesión, recordar los elementos que integran la cesta de la compra, gestionar un pago, almacenar contenidos para la difusión de vídeos o sonido, etc. Además, entre las cookies técnicas se incluyen aquellas que permiten recordar información configurada por el usuario en el portal web para que el mismo acceda al servicio con determinadas características que pueden diferenciar su experiencia de la de otros usuarios, como por ejemplo el idioma seleccionado por el usuario, el tipo de navegación y configuración regional a través de la cual accede, etc. Las cookies técnicas son estrictamente necesarias para proporcionar los servicios de la web, así como para su correcto funcionamiento, por ello no es posible rechazar su uso.

Cookies de personalización:

Las cookies de personalización se utilizan para mostrar una experiencia personalizada al usuario que visita la web, utilizando parámetros no seleccionados específicamente por el usuario, como por ejemplo información obtenida del dispositivo desde el que se navega o información obtenida a través de otras interacciones del usuario con Telefónica (por ejemplo, si eres cliente, los productos que tienes contratados).

Cookies de Análisis:

Las cookies analíticas propias, son aquellas que permiten a 4Geeks realizar el seguimiento y análisis del comportamiento de los usuarios de la página web. La información recogida mediante este tipo de cookies se utiliza en la medición de la actividad del sitio web, con el fin de introducir mejoras en función del análisis de los datos de uso que hacen los usuarios del servicio. Utilizamos cookies analíticas propias, principalmente utilizando los servicios y herramientas de Google Analytics, para las finalidades mencionadas anteriormente.

Cookies de publicidad:
Las cookies de publicidad son aquellas que permiten, a través de ciertos datos asignados u obtenidos del dispositivo de un usuario, almacenar o compartir con terceros, información del comportamiento de los usuarios, obtenida a través de la observación de sus hábitos de navegación, lo que permite desarrollar un perfil específico. Utilizamos cookies propias y de terceros como Facebook, LinkedIn, Google para, a través de la información que reciben de los usuarios de nuestra web, poder mejorar y optimizar nuestras campañas publicitarias en sus plataformas.

Each explanation must have a link where we can view with all details each cookie, like this:

![image](https://user-images.githubusercontent.com/62053368/103678870-66912e00-4f84-11eb-9d48-ca799b07e391.png)
![image](https://user-images.githubusercontent.com/62053368/103679268-ecad7480-4f84-11eb-9fd0-9e8a821e3b96.png)

**Comment by ArielCalisaya** [comment]
### I have opened a [Pull Request](https://github.com/4GeeksAcademy/website-v2/pull/488#issuecomment-770290095) #488 where it solves all the requirements of this issue.

**It only needs a review and authorization.**
