### ISSUE TITLE
Apply Test automation "Cypress" on the web page

### ISSUE THREAD

**Issue by ArielCalisaya** [4GeeksAcademy/website-v2#493]
Hrs <hrs>8</hrs>

The project needs to apply automated test processes where it will be necessary to use  [Cypress.io](https://www.cypress.io/) and integrate it together with gatsby

**Comment by plucodev** [comment]
Hrs Estimated: <hrs>10</hrs>

**Comment by ArielCalisaya** [comment]
A Pull Request [DragScrollProvider and Cypress](https://github.com/4GeeksAcademy/website-v2/pull/497) has been opened and is waiting for approval

**Comment by alesanchezr** [comment]
por pagar
