### ISSUE TITLE
DRAGGABLE DIV COMPONENT

### ISSUE THREAD

**Issue by plucodev** [4GeeksAcademy/website-v2#494]
Hrs <hrs>6</hrs>

**Comment by plucodev** [comment]
create a new component which inherit from the existing Div one inside Sections.js.
This component needs to allow to drag the div so we can use in the horizontal slider
<img width="934" alt="Screen Shot 2021-02-10 at 11 26 50 AM" src="https://user-images.githubusercontent.com/44124290/107539442-f84b1700-6b92-11eb-8e2e-488e34bc95f4.png">

**Comment by plucodev** [comment]
Hrs Estimated: <hrs>4</hrs>

**Comment by ArielCalisaya** [comment]
Here's my [PR](https://github.com/4GeeksAcademy/website-v2/pull/497)

**Comment by alesanchezr** [comment]
Hrs: <hrs>6</hrs>

**Comment by alesanchezr** [comment]
por pagar
