### ISSUE TITLE
Reject weird phone numbers

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#519]
Hrs <hrs>7</hrs>

Validate for weird fake numbers and email on the apply or request syllabus form.

- Phone: 9999999 (same digits)
- Phone: 123123123 
- any email from mailinator.com
- any other spam emails?

Do research about these type of fake numbers and how to recognize them.

You function must be written inside the actions.js file and it must be used by any phone or email input respectively.

**Comment by ArielCalisaya** [comment]
A PR #556 is waiting for review

**Comment by plucodev** [comment]
Added 1 hour to implement Cypress test for phone and email

**Comment by alesanchezr** [comment]
I just tried applying to the academy on the preview link that shows up on this PR #521 and it allowed me to apply, no error.
