### ISSUE TITLE
Cuando hago FORk del repositorio y voy a landings me encuentro con este error

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#559]
Esto aparece cuando en el fork que he hecho de la última versión del repo de la web, voy a landings y luego a hago clic en cualquiera de ellos

![image (7)](https://user-images.githubusercontent.com/62053368/111510653-47fe9e80-874e-11eb-98e0-cebcd5799295.png)

**Comment by alesanchezr** [comment]
No logro replicar esto, te sigue pasando?

**Comment by victormgomezp** [comment]
No. Ya no ha pasado más.


| Victor Manuel Gómez Pérez
| Country Manager Spain
| (+34) 684 33 25 81
| www.4GeeksAcademy.com
