### ISSUE TITLE
Why 4Geeks Videos Dont work

### ISSUE THREAD

**Issue by victormgomezp** [4GeeksAcademy/website-v2#657]
Hrs: <hrs>1</hrs>

Both, in spanish and english videos don't work in Why 4Geeks Section

![image](https://user-images.githubusercontent.com/62053368/114694183-93d74000-9d1a-11eb-8279-8e73aa79b94f.png)

**Comment by ArielCalisaya** [comment]
Fixed issue in PR #660 and is waiting for review
