### ISSUE TITLE
General - Replace "Awards and Recognitions" Icons

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/website-v2#665]
Hrs: <hrs>0.5</hrs>
The award and recognition icons have been updated. We need to replace them of all screens that used these icons.

The screens where they should be replaced are:

- Home.
- Programs.
- Campuses.
- Why 4Geeks?.
- Award and recognition.
- About the Academy.
- Partnership.

The new icons are updated in the screens of "Approval Screens" page on Figma.

**Comment by ArielCalisaya** [comment]
updated on PR #677

**Comment by Andrearcastillo** [comment]
@ArielCalisaya I can't see this adjustment yet. I need to review it in https://next.4geeksacademy.com/ ?

**Comment by csadotav** [comment]
@Andrearcastillo The Pull request is waiting to merge, but you can review the changes in the [Live Preview](https://website-v2-gkytchk22-geeksacademy.vercel.app/)

**Comment by Andrearcastillo** [comment]
Hi @plucodev @csadotav ! In yesterday's merged version, I still can't see this adjustment that Ariel already made.

**Comment by ArielCalisaya** [comment]
@Andrearcastillo The Pull Request is still open, so the new changes have yet to be merged.
I will notify @plucodev to merge as soon as possible

**Comment by ArielCalisaya** [comment]
@Andrearcastillo The next branch has been merged and updated with the changes of PR #677
