### ISSUE TITLE
Home Header- Remove dropdown in the Button

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/website-v2#667]
Hrs: <hrs>0.5</hrs>
Remove the dropdown programs from the button. If the user clicks the button, the page will automatically scroll down to the programs section within the home page.
![image](https://user-images.githubusercontent.com/80764131/114914762-1b937c00-9df9-11eb-946c-cef3609b9321.png)

Scroll down to this section.
![image](https://user-images.githubusercontent.com/80764131/114914813-29490180-9df9-11eb-82b3-89dd43ea6d59.png)

**NOTE: No button within the new website works as a dropdown. Just trigger an action.**

Action Example clicking in "THE RECAP" in the menu: https://digitalagencyday.com/2017/

**Comment by ArielCalisaya** [comment]
PR #681 is waiting to merge

**Comment by Andrearcastillo** [comment]
@ArielCalisaya  @plucodev  Hi guys, checking next.webs ..... I saw you made the adjustment. However, by clicking the button, it makes an automatic "jump" to the program section, this is fine, but it is not clear if I continue on the same home page. Can we implement an "automatic scroll down" and not a "jump" ?, so the user can see the scroll down path on the home page. Please see this example (click on The Recab in the menu): https://digitalagencyday.com/2017/

**Comment by ArielCalisaya** [comment]
@Andrearcastillo It is because the new changes have not yet been applied, since the Pull Request has not yet been merged
you an test the changes [here](https://website-v2-git-fork-arielcalisaya-feature-programs-a-2add4d.vercel.app/)
