### ISSUE TITLE
Home - Awards Section 

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/website-v2#668]
The font style for this section is Lato Light 22 px. It is currently in Regular version. 

And we need to give the component space, adjust the top and bottom padding. So space it from testimonials and Why 4geeks.

**Current Version**
<img width="1365" alt="Captura de Pantalla 2021-04-15 a la(s) 02 49 02 p  m" src="https://user-images.githubusercontent.com/80764131/114915286-bd1acd80-9df9-11eb-86d8-79be18786c4b.png">

**Design Version**
<img width="815" alt="Captura de Pantalla 2021-04-15 a la(s) 02 51 32 p  m" src="https://user-images.githubusercontent.com/80764131/114915565-1682fc80-9dfa-11eb-95e6-0be72b554d75.png">

**Note: I created another issue to replace the awards icons.**

**Comment by mmhgarcia** [comment]
Resolved. 22/04/21
