### ISSUE TITLE
Home - Graduated hired component

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/website-v2#672]
Can we customize the slider component as the proposed design?
![image](https://user-images.githubusercontent.com/80764131/115070482-5f56b600-9ecb-11eb-9e77-ded0b83d3d37.png)

- Adjusting the width to 8 columns of the grid and the blue color to that of the UI Kit (# 0097CD)
![image](https://user-images.githubusercontent.com/80764131/115070519-6b427800-9ecb-11eb-9a6e-bad5b461c4fc.png)

**Comment by ArielCalisaya** [comment]
PR #708  is ready to test and merge
