### ISSUE TITLE
Single Blog - Content Grid Columns

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/website-v2#676]
Currently the blog content is displayed at 100% of the grid.
<img width="1659" alt="Captura de Pantalla 2021-04-16 a la(s) 06 15 53 p  m" src="https://user-images.githubusercontent.com/80764131/115084842-d26a2780-9edf-11eb-8eb3-bcdb7034c148.png">

**The content should occupy only 8 central columns of the grid. The image must also be occupying the 8 columns.**
<img width="830" alt="Captura de Pantalla 2021-04-16 a la(s) 06 11 29 p  m" src="https://user-images.githubusercontent.com/80764131/115084907-e44bca80-9edf-11eb-8fb9-800e7de64d82.png">

**Comment by ArielCalisaya** [comment]
PR #719 has been created and added the necessary features for a best responsive design
