### ISSUE TITLE
Partnership Page - Header

### ISSUE THREAD

**Issue by Andrearcastillo** [4GeeksAcademy/website-v2#717]
1. Replace the image with the following image(it's the same but this one has better quality):
![Header-Partnership](https://user-images.githubusercontent.com/80764131/116568515-ebf77000-a8de-11eb-8369-0bbb6d5712ff.png)

2. Can we use the original circles in .svg? The circles are ok but the original distribution is different.

3. The "JOIN OUR PARTNERSHIP NETWORK" button in the header currently goes to a modal form. That form is now in at the bottom of this landing. The action of this button is to make an automatic scroll to that form as we did with the "See Programs" button in the header. And remove that modal with the form.

Scroll down to this part
<img width="1317" alt="Captura de Pantalla 2021-04-29 a la(s) 12 20 56 p  m" src="https://user-images.githubusercontent.com/80764131/116575826-64f9c600-a8e5-11eb-9582-757ea9261edf.png">

*Take care of the style buttons, the internal padding of the "send" button it's different. I created an issue for this*

**Comment by plucodev** [comment]
@Andrearcastillo issue fixed. You can check here: 
https://next.4geeksacademy.com/us/partners
