### ISSUE TITLE
This horizontal bar should be moving slowly and the scroll bar should be hidden and I should be able to drag&drop to scroll slowly and the scroll bar should be hidden and I should be able to drag&drop to scroll

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/website-v2#749]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3073-25817-a6a020fbd56cb361a40107cfe9d184cf) 

---
**Source URL**:
[https://next.4geeksacademy.com/](https://next.4geeksacademy.com/)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 90.0.4430.93</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.7 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>1357x690</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by ArielCalisaya** [comment]
- [x] Drag&Drop function
- [x] Hide Scroll
- [ ] Horizontal bar should be moving slowly (In progress)
