### ISSUE TITLE
The upcoming cohorts dates for Santiago are wrong 

### ISSUE THREAD

**Issue by Omonroy36** [4GeeksAcademy/website-v2#928]
In the following section of the webpage the upcoming cohorts dates doesnt match those of the syllabus.
![image](https://user-images.githubusercontent.com/33846362/119543878-24b02b00-bd5f-11eb-8eee-9beef99755e2.png)

This is very important since leads are asking about it, please urgent fix.

**Comment by Omonroy36** [comment]
@plucodev @alesanchezr

**Comment by jatv93** [comment]
This is the current website, it's important to fix it as soon as possible @plucodev @alesanchezr

**Comment by alesanchezr** [comment]
Its fixed in the new website.
